import { Permissions } from './types';

export const DEFAULT_PERMISSIONS: Permissions = {
    accessAll: false,
    dashboard: false,
    attendance: {
        enabled: false,
        daily: 'UserOnly',
        adminAllowance: 'UserOnly',
        petService: 'UserOnly',
        overtime: 'UserOnly',
        undertime: 'UserOnly',
    },
    tripMonitor: {
        enabled: false,
        monitor: 'UserOnly',
        itinerary: 'UserOnly',
        expenses: 'UserOnly',
        truckSummary: false,
    },
    clients: false,
    billing: {
        enabled: false,
        generateSoa: false,
        history: 'UserOnly',
        summary: 'UserOnly',
        analytics: 'UserOnly',
    },
    hr: {
        enabled: false,
        profile201: false,
        livePayroll: false,
        holidays: false,
        generatedPayroll: 'UserOnly',
        iponPondo: 'UserOnly',
        loansApplication: 'UserOnly',
        loansSummary: 'UserOnly',
    },
    fleet: {
        enabled: false,
        truckList: false,
        maintenance: false,
        inspection: false,
        maintSummary: false,
        inventory: false,
        releasing: false,
        history: false,
        insurance: false,
    },
    finance: {
        enabled: false,
        banks: 'UserOnly',
        companyLoans: false,
        investorReport: 'UserOnly',
    },
    systemAdmin: false,
};

export const ADMIN_PERMISSIONS: Permissions = {
    accessAll: true,
    dashboard: true,
    attendance: {
        enabled: true,
        daily: 'All',
        adminAllowance: 'All',
        petService: 'All',
        overtime: 'All',
        undertime: 'All',
    },
    tripMonitor: {
        enabled: true,
        monitor: 'All',
        itinerary: 'All',
        expenses: 'All',
        truckSummary: true,
    },
    clients: true,
    billing: {
        enabled: true,
        generateSoa: true,
        history: 'All',
        summary: 'All',
        analytics: 'All',
    },
    hr: {
        enabled: true,
        profile201: true,
        livePayroll: true,
        holidays: true,
        generatedPayroll: 'All',
        iponPondo: 'All',
        loansApplication: 'All',
        loansSummary: 'All',
    },
    fleet: {
        enabled: true,
        truckList: true,
        maintenance: true,
        inspection: true,
        maintSummary: true,
        inventory: true,
        releasing: true,
        history: true,
        insurance: true,
    },
    finance: {
        enabled: true,
        banks: 'All',
        companyLoans: true,
        investorReport: 'All',
    },
    systemAdmin: true,
};
